if !(isServer) exitWith {};
clearmagazinecargoglobal _this;
clearweaponcargoglobal _this;
clearitemcargoglobal _this;
clearbackpackcargoglobal _this;
_this addweaponcargoglobal ["arifle_MX_Black_F", 9];
_this addweaponcargoglobal ["hgun_Rook40_F", 9];
_this addweaponcargoglobal ["Rangefinder", 2];
_this addweaponcargoglobal ["Binocular", 4];
_this additemcargoglobal ["ItemGPS", 6];
_this additemcargoglobal ["FirstAidKit", 12];
_this additemcargoglobal ["optic_Aco", 9];
_this additemcargoglobal ["Medikit", 3];
_this addbackpackcargoglobal ["B_AssaultPack_rgr", 9];
_this additemcargoglobal ["B_UavTerminal", 1];
_this addbackpackcargoglobal ["B_UAV_01_backpack_F", 1];
_this addmagazinecargoglobal ["16Rnd_9x21_Mag", 40];
_this addmagazinecargoglobal ["30Rnd_65x39_caseless_mag", 200];
_this addmagazinecargoglobal ["SmokeShell", 12];
_this addmagazinecargoglobal ["SmokeShellBlue", 12];
_this addmagazinecargoglobal ["SmokeShellPurple", 12];
_this addmagazinecargoglobal ["Chemlight_Yellow", 12];
_this addmagazinecargoglobal ["Chemlight_Blue", 12];