if !(isServer) exitWith {};
clearmagazinecargoglobal _this;
clearweaponcargoglobal _this;
clearitemcargoglobal _this;
clearbackpackcargoglobal _this;
_this addmagazinecargoglobal ["20Rnd_762x51_Mag", 50];
_this addweaponcargoglobal ["srifle_DMR_03_F", 2];
_this additemcargoglobal ["U_B_FullGhillie_lsh", 6];
_this additemcargoglobal ["U_BG_Guerrilla_6_1", 6];
_this additemcargoglobal ["U_B_GhillieSuit", 6];
_this additemcargoglobal ["muzzle_snds_B", 2];
_this additemcargoglobal ["U_B_Wetsuit", 6];
_this additemcargoglobal ["G_Diving", 6];