if !(isServer) exitWith {};
clearmagazinecargoglobal _this;
clearweaponcargoglobal _this;
clearitemcargoglobal _this;
clearbackpackcargoglobal _this;
_this addweaponcargoglobal ["arifle_MX_F", 18];
_this addweaponcargoglobal ["LMG_Mk200_F", 6];
_this addmagazinecargoglobal ["30Rnd_65x39_caseless_mag", 600];
_this addmagazinecargoglobal ["200Rnd_65x39_cased_Box_Tracer", 18];
_this additemcargoglobal ["acc_flashlight", 25];
_this additemcargoglobal ["bipod_01_F_snd", 6];