if !(isServer) exitWith {};
clearmagazinecargoglobal _this;
clearweaponcargoglobal _this;
clearitemcargoglobal _this;
clearbackpackcargoglobal _this;
_this addweaponcargoglobal ["Rangefinder", 2];
_this additemcargoglobal ["ItemGPS", 2];
_this addweaponcargoglobal ["arifle_MXC_Black_F", 6];
_this addweaponcargoglobal ["srifle_EBR_F", 2];
_this addweaponcargoglobal ["LMG_Zafir_F", 2];
_this additemcargoglobal ["bipod_01_F_blk", 2];
_this additemcargoglobal ["optic_Aco", 6];
_this additemcargoglobal ["optic_SOS", 4];
_this addmagazinecargoglobal ["SmokeShell", 12];
_this addmagazinecargoglobal ["SmokeShellRed", 12];
_this addmagazinecargoglobal ["SmokeShellPurple", 12];
_this addmagazinecargoglobal ["Chemlight_Yellow", 12];
_this addmagazinecargoglobal ["Chemlight_Red", 12];