if !(isServer) exitWith {};
clearmagazinecargoglobal _this;
clearweaponcargoglobal _this;
clearitemcargoglobal _this;
clearbackpackcargoglobal _this;
_this addweaponcargoglobal ["Rangefinder", 2];
_this additemcargoglobal ["ItemGPS", 2];
_this addweaponcargoglobal ["arifle_MXC_Black_F", 6];
_this addweaponcargoglobal ["srifle_EBR_F", 2];
_this addweaponcargoglobal ["LMG_Zafir_F", 2];
_this additemcargoglobal ["bipod_01_F_blk", 2];
_this addmagazinecargoglobal ["30Rnd_65x39_caseless_mag", 200];
_this addmagazinecargoglobal ["150Rnd_762x54_Box_Tracer", 40];
_this addmagazinecargoglobal ["20Rnd_762x51_Mag", 50];
_this addbackpackcargoglobal ["B_Kitbag_cbr", 6];
_this addbackpackcargoglobal ["I_GMG_01_weapon_F", 2];
_this addbackpackcargoglobal ["I_HMG_01_weapon_F", 4];
_this addbackpackcargoglobal ["I_HMG_01_support_F", 6];
_this addbackpackcargoglobal ["I_Mortar_01_weapon_F", 2];
_this addbackpackcargoglobal ["I_Mortar_01_support_F", 2];
_this additemcargoglobal ["MineDetector", 2];
_this additemcargoglobal ["optic_Aco", 4];
_this additemcargoglobal ["optic_mrco", 2];
_this additemcargoglobal ["optic_SOS", 2];
_this additemcargoglobal ["U_BG_Guerrilla_6_1", 6];
_this addmagazinecargoglobal ["SmokeShell", 12];
_this addmagazinecargoglobal ["SmokeShellBlue", 12];
_this addmagazinecargoglobal ["SmokeShellPurple", 12];
_this addmagazinecargoglobal ["Chemlight_Yellow", 12];
_this addmagazinecargoglobal ["Chemlight_Blue", 12];