if !(isServer) exitWith {};
clearmagazinecargoglobal _this;
clearweaponcargoglobal _this;
clearitemcargoglobal _this;
clearbackpackcargoglobal _this;
_this addweaponcargoglobal ["arifle_MX_Black_F", 2];
_this addweaponcargoglobal ["LMG_Mk200_F", 1];
_this addweaponcargoglobal ["Binocular", 1];
_this addmagazinecargoglobal ["SmokeShell", 18];
_this addmagazinecargoglobal ["SmokeShellRed", 18];
_this addmagazinecargoglobal ["SmokeShellOrange", 18];
_this addmagazinecargoglobal ["Chemlight_Yellow", 18];
_this addmagazinecargoglobal ["Chemlight_Red", 18];
_this addmagazinecargoglobal ["30Rnd_65x39_caseless_mag", 80];
_this addmagazinecargoglobal ["200Rnd_65x39_cased_Box_Tracer", 10];
_this additemcargoglobal ["optic_Aco", 3];
_this additemcargoglobal ["bipod_01_F_blk", 1];
_this additemcargoglobal ["acc_flashlight", 3];
_this addbackpackcargoglobal ["B_AssaultPack_rgr", 3];
_this addbackpackcargoglobal ["B_Kitbag_rgr", 3];
_this additemcargoglobal ["U_BG_Guerrilla_6_1", 3];