if !(isServer) exitWith {};
clearmagazinecargoglobal _this;
clearweaponcargoglobal _this;
clearitemcargoglobal _this;
clearbackpackcargoglobal _this;
_this additemcargoglobal ["optic_Aco", 3];
_this addweaponcargoglobal ["arifle_MX_GL_Black_F", 2];
_this addweaponcargoglobal ["Rangefinder", 3];
_this addweaponcargoglobal ["launch_NLAW_F", 2];
_this addweaponcargoglobal ["launch_B_Titan_F", 2];
_this addmagazinecargoglobal ["1Rnd_HE_Grenade_shell", 18];
_this addmagazinecargoglobal ["UGL_FlareWhite_F", 18];
_this addmagazinecargoglobal ["UGL_FlareRed_F", 18];
_this addmagazinecargoglobal ["1Rnd_Smoke_Grenade_shell", 18];
_this addmagazinecargoglobal ["1Rnd_SmokeRed_Grenade_shell", 18];
_this addmagazinecargoglobal ["1Rnd_SmokeOrange_Grenade_shell", 18];
_this addmagazinecargoglobal ["NLAW_F", 8];
_this addmagazinecargoglobal ["Titan_AA", 4];
_this addmagazinecargoglobal ["SatchelCharge_Remote_Mag", 6];
_this addmagazinecargoglobal ["ATMine_Range_Mag", 6];
_this addmagazinecargoglobal ["APERSMine_Range_Mag", 18];
_this addmagazinecargoglobal ["ClaymoreDirectionalMine_Remote_Mag", 6];
_this addmagazinecargoglobal ["DemoCharge_Remote_Mag", 6];
_this addmagazinecargoglobal ["HandGrenade", 18];
_this addmagazinecargoglobal ["30Rnd_65x39_caseless_mag", 60];
_this addbackpackcargoglobal ["B_AssaultPack_rgr", 3];
_this addbackpackcargoglobal ["B_Kitbag_rgr", 3];
_this additemcargoglobal ["acc_flashlight", 3];
_this additemcargoglobal ["MineDetector", 2];
_this additemcargoglobal ["ItemGPS", 3];