if !(isServer) exitWith {};
clearmagazinecargoglobal _this;
clearweaponcargoglobal _this;
clearitemcargoglobal _this;
clearbackpackcargoglobal _this;
_this addweaponcargoglobal ["arifle_MX_Black_F", 5];
_this addweaponcargoglobal ["LMG_Mk200_F", 2];
_this addweaponcargoglobal ["Binocular", 2];
_this addmagazinecargoglobal ["SmokeShell", 28];
_this addmagazinecargoglobal ["SmokeShellRed", 28];
_this addmagazinecargoglobal ["SmokeShellOrange", 28];
_this addmagazinecargoglobal ["Chemlight_Yellow", 28];
_this addmagazinecargoglobal ["Chemlight_Red", 28];
_this addmagazinecargoglobal ["30Rnd_65x39_caseless_mag", 165];
_this addmagazinecargoglobal ["200Rnd_65x39_cased_Box_Tracer", 20];
_this additemcargoglobal ["optic_Aco", 7];
_this additemcargoglobal ["bipod_01_F_snd", 2];
_this additemcargoglobal ["acc_flashlight", 7];
_this addbackpackcargoglobal ["B_AssaultPack_rgr", 7];
_this addbackpackcargoglobal ["B_Kitbag_rgr", 7];
_this additemcargoglobal ["U_BG_Guerrilla_6_1", 7];